default: &default
  adapter: postgresql
  encoding: unicode
  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  #テキスト通り記述しておいた方がいい？
  template: template0

development:
  <<: *default
  database: exercises_development

test:
  <<: *default
  database: exercises_test

production:
  <<: *default
  database: exercises_production
  username: exercises
  password: <%= ENV['EXERCISES_DATABASE_PASSWORD'] %>
